--- #YAML:1.0
name:               RRD-Editor
version:            0.10_1
abstract:           Portable, standalone (no need for RRDs.pm) tool to create and edit RRD files.
author:
    - Doug Leith <dougleith@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
